# Generated by Django 4.1.2 on 2022-10-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='image/', verbose_name='Картинка')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('price', models.FloatField()),
                ('pub_date', models.DateTimeField()),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
    ]
