# Generated by Django 2.2.16 on 2022-10-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
